# theme: jekyll-theme-minimal

exclude:
  - README.md
  - node_modules

markdown: kramdown
highlighter: rouge

# Configure the custom collection
collections:
  projects:
    output: true
    permalink: /categories/projects/:title/ # Define how URLs are generated for projects
  categories:
    output: true
    permalink: /categories/:title/

# Set default values for the projects collection
defaults:
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: project # Set a custom layout (e.g., project.html) for your projects
      author: "Leonardo Ferrisi"
  - scope:
      path: "_categories"
      type: categories
    values:
      layout: category_page # Set a custom layout (e.g., category.html) for your categories
      author: "Leonardo Ferrisi"


# Pagination settings (optional, if you want to paginate project listings)
paginate: 5
paginate_path: "/projects/page:num/"

# Optional: customize the appearance of your projects
# For example, by including them in navigation links
header_pages:
  - index.html
  - _projects
  - _categories
